name: Atualizar dados LotoLab (CAIXA)

on:
  schedule:
    # 12:05 BRT ~ 15:05 UTC
    - cron: "5 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch & build JSON (Mega-Sena + Lotofácil)
        run: node scripts/fetch_loterias_from_caixa.mjs

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/mega.json data/loto.json
          git commit -m "Atualiza dados loterias (automático)"
          git push
